name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: "sudo apt-get install -y build-essential automake autoconf flex check llvm-dev pkg-config zlib1g-dev libdw-dev libffi-dev"
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 5.1.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build everything
        run: "bazel build //..."
